[profile.default]
gas_reports=[
    "PufferDepositor",
    "PufferOracle",
    "PufferVault",
    "PufferVaultV2",
    "PufferDepositorV2",
    "PufferProtocol",
    "GuardianModule",
    "RestakingOperator",
    "EnclaveVerifier",
    "PufferModuleManager",
    "PufferModule",
    "ValidatorTicket"
]
allow_paths = ["../node_modules", "./node_modules"]
block_number = 0 # Our RAVE evidence is generated for blockhash(0) which is bytes32(0)
fs_permissions = [{ access = "read-write", path = "./"}]
src = "src"
out = "out"
libs = ["lib"]
extra_output = ["storageLayout"]
auto_detect_solc = false
ffi = true
ast = true
build_info = true
useLiteralContent = false
optimizer = true
optimizer_runs = 200
evm_version = "cancun" # is live on mainnet
seed = "0x1337"
solc = "0.8.28"
# via_ir = true

[fmt]
line_length = 120
int_types = "long"
tab_width = 4
quote_style = "double"
bracket_spacing = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
mainnet="${ETH_RPC_URL}"
holesky="${HOLESKY_RPC_URL}"
sepolia="${SEPOLIA_RPC_URL}"
opsepolia ="${OP_SEPOLIA_RPC_URL}"

[invariant]
fail_on_revert=false
depth = 110
runs = 50

[fuzz]
runs = 100

[profile.ci.fuzz]
runs = 50000
seed = ""